services:
  - type: web
    name: slopesense-backend
    env: docker
    dockerfilePath: SlopeSense/backend/Dockerfile
    branch: main
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3003"
      - key: PYTHON_PATH
        value: "/usr/bin/python3"
